<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Student.aspx.cs" Inherits="RegistrationForm.Student" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div style="height: 118px; width: 713px">
            <h1>Demo page</h1>
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        </div>
        <asp:GridView ID="GridView1" runat="server" DataKeyNames="StudentId" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateDeleteButton="true" >
         <Columns>  
             
                <asp:BoundField DataField="StudentId" HeaderText="Student Id" />  
                <asp:BoundField DataField="StudentName" HeaderText="First Name" />  
                <asp:BoundField DataField="LastName" HeaderText="Last Name" />  
                <asp:BoundField DataField="MiddleName" HeaderText="Middle Name" />  
                <asp:BoundField DataField="Sibling" HeaderText="Sibling" />  
                <asp:BoundField DataField="AddressP" HeaderText="Address" />  
                <asp:BoundField DataField="FatherName" HeaderText="Father Name" />  
                <asp:BoundField DataField="Qualification" HeaderText="Mother Qualification" />  
                <asp:BoundField DataField="MotherName" HeaderText="Mother Name" />  
                <asp:BoundField DataField="MotherQualification" HeaderText="Mother Qualification" />  
                
            </Columns>  
            <HeaderStyle BackColor="#0066cc" Font-Bold="true" ForeColor="White" />  
            <RowStyle BackColor="#bfdfff" ForeColor="Black" />  
        </asp:GridView>
    </form>
</body>
</html>
