<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Display.aspx.cs" Inherits="SchoolRegistrationForm.Display" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>

            <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
            <br />
            <br />
            <asp:GridView ID="GridView1" runat="server" DataKeyNames="StudentId" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateDeleteButton="True" AutoGenerateColumns="False" OnRowSelect="OnRowSelect" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" >
               <Columns>  
                <asp:BoundField DataField="StudentId" HeaderText="Student Id" />

                <asp:BoundField DataField="Sibling" HeaderText="Sibling" />
                <asp:BoundField DataField="AdmissionNo" HeaderText="Admission No" />
                <asp:BoundField DataField="SiblingName" HeaderText="Sibling Name" />
                <asp:BoundField DataField="SiblingClass" HeaderText="Sibling Class" />

                <asp:BoundField DataField="StudentFirstName" HeaderText="Student First Name" />
                <asp:BoundField DataField="LastName" HeaderText="Last Name" />
                <asp:BoundField DataField="MiddleName" HeaderText="Middle Name" />
                <asp:BoundField DataField="Gender" HeaderText="Gender" />
                <asp:BoundField DataField="DOB" HeaderText="DOB" />
                <asp:BoundField DataField="AcademicYear" HeaderText="Academic Year" />
                <asp:BoundField DataField="StudentType" HeaderText="Student Type" />
                <asp:BoundField DataField="Class" HeaderText="Class" />
                <asp:BoundField DataField="MotherTongue" HeaderText="Mother Tongue" />
                <asp:BoundField DataField="StudentEmailId" HeaderText="Student EmailId" />
                <asp:BoundField DataField="Religion" HeaderText="Religion" />
                <asp:BoundField DataField="PreviousSchool" HeaderText="PreviousSchool" />
                <asp:BoundField DataField="MobileNo" HeaderText="MobileNo" />
                <asp:BoundField DataField="Telephone" HeaderText="Telephone" />
                <asp:BoundField DataField="Nationality" HeaderText="Nationality" />
                <asp:BoundField DataField="StudentPhoto" HeaderText="StudentPhoto" />

                <asp:BoundField DataField="AddressP" HeaderText="Address" />
                <asp:BoundField DataField="CityP" HeaderText="City" />
                <asp:BoundField DataField="PinCodeP" HeaderText="PinCode" />
                <asp:BoundField DataField="StateP" HeaderText="State" />
                <asp:BoundField DataField="PermTemp" HeaderText="PermTemp" />
                <asp:BoundField DataField="AddressT" HeaderText="Address" />
                <asp:BoundField DataField="CityT" HeaderText="City" />
                <asp:BoundField DataField="PinCodeT" HeaderText="PinCode" />
                <asp:BoundField DataField="StateT" HeaderText="State" />
                <asp:BoundField DataField="CountryT" HeaderText="Country" />

                <asp:BoundField DataField="FatherName" HeaderText="Father Name" />
                <asp:BoundField DataField="Qualification" HeaderText="Qualification" />
                <asp:BoundField DataField="FatherMobileno" HeaderText="Father Mobile no" />
                <asp:BoundField DataField="FatherOfficeAddress" HeaderText="OfficeAddress" />
                <asp:BoundField DataField="FatherEmailId" HeaderText="EmailId" />
                <asp:BoundField DataField="FatherTelephone" HeaderText="Telephone" />
                <asp:BoundField DataField="FatherOccupation" HeaderText="Occupation" />
                <asp:BoundField DataField="FatherModernite" HeaderText="Father Modernite" />
                <asp:BoundField DataField="FatherModerniteYear" HeaderText="Father Modernite Year" />
                <asp:BoundField DataField="FatherModerniteBranch" HeaderText="Father Modernite Branch" />
                <asp:BoundField DataField="FatherPhoto" HeaderText="Father Photo" />

                <asp:BoundField DataField="MotherName" HeaderText="Mother Name" />
                <asp:BoundField DataField="MotherQualification" HeaderText="Mother Qualification" />
                <asp:BoundField DataField="MotherMobileno" HeaderText="Mother Mobile No" />
                <asp:BoundField DataField="MotherOfficeAddress" HeaderText="Office Address" />
                <asp:BoundField DataField="MotherEmailId" HeaderText="Mother EmailId" />
                <asp:BoundField DataField="MotherTelephone" HeaderText="Mother Telephone" />
                <asp:BoundField DataField="MotherOccupation" HeaderText="Mother Occupation" />
                <asp:BoundField DataField="MotherModernite" HeaderText="Mother Modernite" />
                <asp:BoundField DataField="MotherModerniteYear" HeaderText="Mother Modernite Year" />
                <asp:BoundField DataField="MotherModerniteBranch" HeaderText="Mother Modernite Branch" />
                <asp:BoundField DataField="MotherPhoto" HeaderText="Mother Photo" />
             </Columns>  
            <HeaderStyle BackColor="#0066cc" Font-Bold="true" ForeColor="White" />  
            <RowStyle BackColor="#bfdfff" ForeColor="Black" />  
            </asp:GridView>
            <br />
            <br />
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Back" />
        </div>
    </form>
</body>
</html>
